DROP TABLE events IF EXISTS;
drop table users if exists;
drop table location if exists;

CREATE TABLE events (
  id bigint generated by default as identity,
  event_name VARCHAR(100) NOT NULL, 
  date Date NOT NULL,
  time Time NOT NULL,
  description VARCHAR(100) NOT NULL,
  location bigint NOT NULL,
  open boolean NOT NULL,
  creator bigint NOT NULL,
  primary key (id)
);

create table location (
    id bigint generated by default as identity,
    street varchar(50) not null,
    streetNO varchar(50) not null,
    postalcode varchar(50) not null,
    city varchar(50) not null,
    country varchar(50) not null,
    latitude varchar(50) ,
    longitude varchar(50) ,
    primary key (id)
);

create table users (
    id bigint generated by default as identity,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    location bigint NOT NULL,
    email varchar(100) not null,
    password varchar(50) not null,
    primary key (id)
);

alter table users
   add foreign key (location) 
   references location(id);
   
  alter table events
   add foreign key (creator) 
   references users(id);
   
 alter table events  
   add foreign key (location) 
   references location(id);


